/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
/*
import java.awt.Image;
import javax.swing.ImageIcon;*/



/**
 *
 * @author David
 */
public class vAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vVuelos
     */
    public vAdmin() {
        initComponents();
        
        /*this.setLocationRelativeTo(null);
        ImageIcon avion_logo = new ImageIcon(getClass().getResource(("/img/avion_logo.png")));
        ImageIcon usuario = new ImageIcon(getClass().getResource(("/img/usuario.png")));
        
        ImageIcon logotipo = new ImageIcon(avion_logo.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon user = new ImageIcon(usuario.getImage().getScaledInstance(jLabelUsuarioImagen.getWidth(), jLabelUsuarioImagen.getHeight(), Image.SCALE_DEFAULT));
        
        jLabelLogo.setIcon(logotipo);
        jLabelUsuarioImagen.setIcon(user);
        
        Animacion.Animacion.mover_izquierda(1010, 190, 1, 2, jPanelInicio);
        int posicionInicio = this.jPanelInicio.getX();
        System.out.println("Inicio: "+posicionInicio);
        jLabelSeccion.setText("Inicio");
        
        //Íconos a botones//
        ImageIcon agregar = new ImageIcon(getClass().getResource(("/icons/add.png")));
        ImageIcon editar = new ImageIcon(getClass().getResource(("/icons/edit.png")));
        ImageIcon refrescar = new ImageIcon(getClass().getResource(("/icons/refresh.png")));
        ImageIcon eliminar = new ImageIcon(getClass().getResource(("/icons/delete.png")));
        System.out.println("Ancho: " + jButtonAgregarVuelo.getWidth()/4 + "\nAlto: " + jButtonAgregarVuelo.getHeight()/4);
        
        ImageIcon add = new ImageIcon(agregar.getImage().getScaledInstance(jButtonAgregarVuelo.getWidth()/4, jButtonAgregarVuelo.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon edit = new ImageIcon(editar.getImage().getScaledInstance(jButtonModificarVuelo.getWidth()/4, jButtonModificarVuelo.getHeight() - 8, Image.SCALE_DEFAULT));
        ImageIcon refresh = new ImageIcon(refrescar.getImage().getScaledInstance(jButtonRefresh.getWidth(), jButtonRefresh.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon delete = new ImageIcon(eliminar.getImage().getScaledInstance(jButtonEliminarVuelo.getWidth()/4, (jButtonEliminarVuelo.getHeight()/2), Image.SCALE_DEFAULT));
        
        jButtonAgregarVuelo.setIcon(add);
        jButtonModificarVuelo.setIcon(edit);
        jButtonEliminarVuelo.setIcon(delete);
        jButtonRefresh.setIcon(refresh);*/
        /**/
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLabelUsuarioImagen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelNombreUser = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jButtonAviones = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonVentas = new javax.swing.JButton();
        jButtonVuelos = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelSuperior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelNombreLogo = new javax.swing.JLabel();
        jLabelSeccion = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jPanelVuelos = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonAgregarVuelo = new javax.swing.JButton();
        jButtonModificarVuelo = new javax.swing.JButton();
        jButtonEliminarVuelo = new javax.swing.JButton();
        jPanelTablaContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        jPanelHistorialVuelos = new javax.swing.JPanel();
        jBtnHistorialVuelos = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAviones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelUsuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelVentas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContainer.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(128, 0, 0));

        jLabelNombreUser.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        jLabelNombreUser.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNombreUser.setText("Nombre de usuario");

        jButtonInicio.setBackground(new java.awt.Color(255, 0, 0));
        jButtonInicio.setForeground(new java.awt.Color(204, 204, 204));
        jButtonInicio.setText("Inicio");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jButtonAviones.setBackground(new java.awt.Color(128, 0, 0));
        jButtonAviones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAviones.setText("Aviones");
        jButtonAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvionesActionPerformed(evt);
            }
        });

        jButtonUsuarios.setBackground(new java.awt.Color(128, 0, 0));
        jButtonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });

        jButtonVentas.setBackground(new java.awt.Color(128, 0, 0));
        jButtonVentas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVentas.setText("Ventas");
        jButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentasActionPerformed(evt);
            }
        });

        jButtonVuelos.setBackground(new java.awt.Color(128, 0, 0));
        jButtonVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVuelos.setText("Vuelos");
        jButtonVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVuelosActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(128, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cerrar sesión");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelUsuarioImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addComponent(jButtonInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAviones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelUsuarioImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelNombreUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelContainer.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 85, 180, 660));

        jPanelSuperior.setBackground(new java.awt.Color(128, 0, 0));

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelNombreLogo.setFont(new java.awt.Font("Century Schoolbook", 2, 36)); // NOI18N
        jLabelNombreLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreLogo.setText("VOYAGER AIRLINES");

        jLabelSeccion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelSeccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeccion.setText("TEXTO");

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("X");
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addGap(0, 636, Short.MAX_VALUE)
                        .addComponent(jLabelSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addComponent(jLabelNombreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir))))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelContainer.add(jPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 990, 80));

        jPanelVuelos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVuelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregarVuelo.setText("Agregar");
        jPanelOpciones.add(jButtonAgregarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jButtonModificarVuelo.setText("Modificar");
        jPanelOpciones.add(jButtonModificarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 130, 40));

        jButtonEliminarVuelo.setText("Eliminar");
        jPanelOpciones.add(jButtonEliminarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 40));

        jPanelVuelos.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 80));

        jPanelTablaContainer.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTablaContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVuelos);

        javax.swing.GroupLayout jPanelTablaContainerLayout = new javax.swing.GroupLayout(jPanelTablaContainer);
        jPanelTablaContainer.setLayout(jPanelTablaContainerLayout);
        jPanelTablaContainerLayout.setHorizontalGroup(
            jPanelTablaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        jPanelTablaContainerLayout.setVerticalGroup(
            jPanelTablaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        jPanelVuelos.add(jPanelTablaContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 460));

        jPanelHistorialVuelos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHistorialVuelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jBtnHistorialVuelos.setText("Historial de Vuelos");
        jBtnHistorialVuelos.setContentAreaFilled(false);
        jBtnHistorialVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelHistorialVuelosLayout = new javax.swing.GroupLayout(jPanelHistorialVuelos);
        jPanelHistorialVuelos.setLayout(jPanelHistorialVuelosLayout);
        jPanelHistorialVuelosLayout.setHorizontalGroup(
            jPanelHistorialVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnHistorialVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanelHistorialVuelosLayout.setVerticalGroup(
            jPanelHistorialVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnHistorialVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanelVuelos.add(jPanelHistorialVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 140, 75));

        jButtonRefresh.setActionCommand("");
        jButtonRefresh.setContentAreaFilled(false);
        jButtonRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanelVuelos.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 570, 75, 75));

        jPanelContainer.add(jPanelVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 800, 650));

        jPanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Inicio");
        jPanelInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 40, -1));

        jPanelContainer.add(jPanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 800, 650));

        jPanelAviones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAviones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Aviones");
        jPanelAviones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 40, -1));

        jPanelContainer.add(jPanelAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 800, 650));

        jPanelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jPanelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Usuarios");
        jPanelUsuarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, -1));

        jPanelContainer.add(jPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 800, 650));

        jPanelVentas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Ventas");
        jPanelVentas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 40, -1));

        jPanelContainer.add(jPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 800, 650));

        getContentPane().add(jPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVuelosActionPerformed
        // TODO add your handling code here:
        int posicionVuelo = this.jPanelVuelos.getX();
        int posicionVenta = this.jPanelVentas.getX();
        int posicionUsuarios = this.jPanelUsuarios.getX();
        int posicionAviones = this.jPanelAviones.getX();
        int posicionInicio = this.jPanelInicio.getX();
        jLabelSeccion.setText("Vuelos");
        
        if(posicionVenta < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVentas);
        else if(posicionUsuarios < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelUsuarios);
        else if(posicionAviones < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelAviones);
        else if(posicionInicio < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelInicio);
        
        if(posicionVuelo > 200)
            Animacion.Animacion.mover_izquierda(1010, 190, 1, 2, jPanelVuelos);
    }//GEN-LAST:event_jButtonVuelosActionPerformed

    private void jButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentasActionPerformed
        // TODO add your handling code here:
        int posicionVuelo = this.jPanelVuelos.getX();
        int posicionVenta = this.jPanelVentas.getX();
        int posicionUsuarios = this.jPanelUsuarios.getX();
        int posicionAviones = this.jPanelAviones.getX();
        int posicionInicio = this.jPanelInicio.getX();
        
        jLabelSeccion.setText("Ventas");
        
        if(posicionUsuarios < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelUsuarios);
        else if(posicionAviones < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelAviones);
        else if(posicionInicio < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelInicio);
        else if(posicionVuelo < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVuelos);
        
        if(posicionVenta > 200)
            Animacion.Animacion.mover_izquierda(1010, 190, 1, 2, jPanelVentas);
    }//GEN-LAST:event_jButtonVentasActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
        int posicionVuelo = this.jPanelVuelos.getX();
        int posicionVenta = this.jPanelVentas.getX();
        int posicionUsuarios = this.jPanelUsuarios.getX();
        int posicionAviones = this.jPanelAviones.getX();
        int posicionInicio = this.jPanelInicio.getX();
        
        jLabelSeccion.setText("Inicio");
        
        if(posicionVenta < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVentas);
        else if(posicionUsuarios < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelUsuarios);
        else if(posicionAviones < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelAviones);
        else if(posicionVuelo < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVuelos);
        
        if(posicionInicio > 200)
            Animacion.Animacion.mover_izquierda(1010, 190, 1, 2, jPanelInicio);
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvionesActionPerformed
        // TODO add your handling code here:
        int posicionVuelo = this.jPanelVuelos.getX();
        int posicionVenta = this.jPanelVentas.getX();
        int posicionUsuarios = this.jPanelUsuarios.getX();
        int posicionAviones = this.jPanelAviones.getX();
        int posicionInicio = this.jPanelInicio.getX();
        
        jLabelSeccion.setText("Aviones");
        
        if(posicionVenta < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVentas);
        else if(posicionUsuarios < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelUsuarios);
        else if(posicionInicio < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelInicio);
        else if(posicionVuelo < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVuelos);
        
        if(posicionAviones > 200)
            Animacion.Animacion.mover_izquierda(1010, 190, 1, 2, jPanelAviones);
    }//GEN-LAST:event_jButtonAvionesActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        // TODO add your handling code here:
        int posicionVuelo = this.jPanelVuelos.getX();
        int posicionVenta = this.jPanelVentas.getX();
        int posicionUsuarios = this.jPanelUsuarios.getX();
        int posicionAviones = this.jPanelAviones.getX();
        int posicionInicio = this.jPanelInicio.getX();
        
        jLabelSeccion.setText("Usuarios");
        
        if(posicionVenta < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVentas);
        else if(posicionAviones < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelAviones);
        else if(posicionInicio < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelInicio);
        else if(posicionVuelo < 300)
            Animacion.Animacion.mover_derecha(190, 1010, 1, 2, jPanelVuelos);
        
        if(posicionUsuarios > 200)
            Animacion.Animacion.mover_izquierda(1010, 190, 1, 2, jPanelUsuarios);
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnHistorialVuelos;
    private javax.swing.JButton jButton6;
    public javax.swing.JButton jButtonAgregarVuelo;
    private javax.swing.JButton jButtonAviones;
    public javax.swing.JButton jButtonEliminarVuelo;
    private javax.swing.JButton jButtonInicio;
    public javax.swing.JButton jButtonModificarVuelo;
    public javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JButton jButtonVuelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreLogo;
    private javax.swing.JLabel jLabelNombreUser;
    public javax.swing.JLabel jLabelSeccion;
    public javax.swing.JLabel jLabelUsuarioImagen;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelAviones;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelHistorialVuelos;
    public javax.swing.JPanel jPanelInicio;
    public javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelOpciones;
    public javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPanel jPanelTablaContainer;
    public javax.swing.JPanel jPanelUsuarios;
    public javax.swing.JPanel jPanelVentas;
    public javax.swing.JPanel jPanelVuelos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables
}
