/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author David
 */
public class vAgregarTripulacion extends javax.swing.JFrame {

    /**
     * Creates new form Trip
     */
    public vAgregarTripulacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSalirAgregar = new javax.swing.JButton();
        lblTituloTripulacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblImgNombre = new javax.swing.JLabel();
        lblPuestoTripulacion = new javax.swing.JLabel();
        lblNumTripulacion = new javax.swing.JLabel();
        txtNombreTripulacion = new javax.swing.JTextField();
        cbxPuesto = new javax.swing.JComboBox<>();
        txtTripulacion = new javax.swing.JTextField();
        btnAceptarTripulacion = new javax.swing.JButton();
        btnLimpiarCamposTripulacion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(213, 216, 223));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(128, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirAgregar.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnSalirAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirAgregar.setText("X");
        btnSalirAgregar.setContentAreaFilled(false);
        btnSalirAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnSalirAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 10, 50, 50));

        lblTituloTripulacion.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblTituloTripulacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTripulacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTripulacion.setText("Agregar miembro de tripulación");
        jPanel3.add(lblTituloTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 496, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 496, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jPanel4.setPreferredSize(new java.awt.Dimension(470, 250));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(lblImgNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 40, 40));
        jPanel4.add(lblPuestoTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 50));
        jPanel4.add(lblNumTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 50, 50));

        txtNombreTripulacion.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        txtNombreTripulacion.setText("Apellido, Nombre");
        txtNombreTripulacion.setToolTipText("Nombre completo");
        jPanel4.add(txtNombreTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 380, 30));

        cbxPuesto.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jPanel4.add(cbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 110, 150, 30));

        txtTripulacion.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        txtTripulacion.setText("No. tripulación");
        txtTripulacion.setToolTipText("Número de tripulación");
        jPanel4.add(txtTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 110, 150, 30));

        btnAceptarTripulacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnAceptarTripulacion.setText("Aceptar");
        jPanel4.add(btnAceptarTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, 90, 30));

        btnLimpiarCamposTripulacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnLimpiarCamposTripulacion.setText("Limpiar campos");
        jPanel4.add(btnLimpiarCamposTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, 470, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 72, 496, 138));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarTripulacion;
    public javax.swing.JButton btnLimpiarCamposTripulacion;
    public javax.swing.JButton btnSalirAgregar;
    public javax.swing.JComboBox<String> cbxPuesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel lblImgNombre;
    public javax.swing.JLabel lblNumTripulacion;
    public javax.swing.JLabel lblPuestoTripulacion;
    public javax.swing.JLabel lblTituloTripulacion;
    public javax.swing.JTextField txtNombreTripulacion;
    public javax.swing.JTextField txtTripulacion;
    // End of variables declaration//GEN-END:variables
}
