/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author David
 */
public class vBuscar_AgregarVuelo extends javax.swing.JFrame {

    /**
     * Creates new form vBuscar_AgregarVuelo
     */
    public vBuscar_AgregarVuelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrarBuscarVuelo = new javax.swing.JButton();
        lblTituloBuscar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAceptarBuscarAvion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatosBuscar = new javax.swing.JTable();
        btnAceptarBuscarTrip = new javax.swing.JButton();
        tablaAvion = new javax.swing.JScrollPane();
        tblNumBuscarAvion = new javax.swing.JTable();
        tablaTripulacion = new javax.swing.JScrollPane();
        tblNumBuscarTripulacion = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(47, 79, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarBuscarVuelo.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCerrarBuscarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarBuscarVuelo.setText("X");
        btnCerrarBuscarVuelo.setContentAreaFilled(false);
        btnCerrarBuscarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnCerrarBuscarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 10, 50, 50));

        lblTituloBuscar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblTituloBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloBuscar.setText("Buscar tripulación / avión");
        jPanel2.add(lblTituloBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 396, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 396, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarBuscarAvion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnAceptarBuscarAvion.setText("Aceptar");
        jPanel5.add(btnAceptarBuscarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 30));

        tblDatosBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parte 1", "Parte 2"
            }
        ));
        tblDatosBuscar.setEnabled(false);
        jScrollPane2.setViewportView(tblDatosBuscar);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 220));

        btnAceptarBuscarTrip.setText("Aceptar");
        jPanel5.add(btnAceptarBuscarTrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 20, 260, 280));

        tblNumBuscarAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. avión"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAvion.setViewportView(tblNumBuscarAvion);

        jPanel3.add(tablaAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 280));

        tblNumBuscarTripulacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. tripulación"
            }
        ));
        tablaTripulacion.setViewportView(tblNumBuscarTripulacion);

        jPanel3.add(tablaTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 280));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 75, 390, 320));

        jPanel4.setBackground(new java.awt.Color(213, 216, 223));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 72, 396, 163));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vBuscar_AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vBuscar_AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vBuscar_AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vBuscar_AgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vBuscar_AgregarVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarBuscarAvion;
    public javax.swing.JButton btnAceptarBuscarTrip;
    public javax.swing.JButton btnCerrarBuscarVuelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblTituloBuscar;
    public javax.swing.JScrollPane tablaAvion;
    public javax.swing.JScrollPane tablaTripulacion;
    public javax.swing.JTable tblDatosBuscar;
    public javax.swing.JTable tblNumBuscarAvion;
    public javax.swing.JTable tblNumBuscarTripulacion;
    // End of variables declaration//GEN-END:variables
}
