/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author David
 */
public class vMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vMenuAdmin
     */
    public vMenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogoIcon = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnSalir = new componente.Boton();
        btnMinimizar = new componente.Boton();
        jPanel3 = new javax.swing.JPanel();
        pnlTripulacion = new javax.swing.JPanel();
        lblTripulacionIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlConfig = new javax.swing.JPanel();
        lblConfigIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlVenta = new javax.swing.JPanel();
        lblVentaIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlUsuario = new javax.swing.JPanel();
        lblUsuarioIcon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlVuelo = new javax.swing.JPanel();
        lblVueloIcon = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlSalir = new javax.swing.JPanel();
        lblSalirIcon = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlAyuda = new javax.swing.JPanel();
        lblAyudaIcon = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlAvion = new javax.swing.JPanel();
        lblAvionIcon = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38), 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(20, 64, 138));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblLogoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 160));

        jLabel18.setFont(new java.awt.Font("Calisto MT", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(245, 245, 245));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("VOYAGER");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 80));

        jLabel19.setFont(new java.awt.Font("Calisto MT", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(245, 245, 245));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("AIRLINES");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 290, 80));

        jLabel20.setFont(new java.awt.Font("Calisto MT", 2, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Vuela como te gusta, vuela con seguridad,");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 400, 40));

        jLabel21.setFont(new java.awt.Font("Calisto MT", 2, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("con Voyager, siempre habrá puntualidad.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 400, 40));

        btnSalir.setBackground(new java.awt.Color(0, 162, 215));
        btnSalir.setColorHover(new java.awt.Color(0, 175, 234));
        btnSalir.setColorNormal(new java.awt.Color(0, 162, 215));
        btnSalir.setColorPressed(new java.awt.Color(0, 143, 191));
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 5, 35, 30));

        btnMinimizar.setBackground(new java.awt.Color(0, 162, 215));
        btnMinimizar.setColorHover(new java.awt.Color(0, 175, 234));
        btnMinimizar.setColorNormal(new java.awt.Color(0, 162, 215));
        btnMinimizar.setColorPressed(new java.awt.Color(0, 143, 191));
        jPanel2.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 5, 35, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 990, 180));

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTripulacion.setBackground(new java.awt.Color(235, 238, 241));
        pnlTripulacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTripulacionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlTripulacion.add(lblTripulacionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tripulación");
        pnlTripulacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 290, 150, 150));

        pnlConfig.setBackground(new java.awt.Color(235, 238, 241));
        pnlConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfigIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlConfig.add(lblConfigIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Configuración");
        pnlConfig.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 290, 150, 150));

        pnlVenta.setBackground(new java.awt.Color(235, 238, 241));
        pnlVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlVenta.add(lblVentaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ventas");
        pnlVenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 70, 150, 150));

        pnlUsuario.setBackground(new java.awt.Color(235, 238, 241));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuarioIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlUsuario.add(lblUsuarioIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Usuarios");
        pnlUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 70, 150, 150));

        pnlVuelo.setBackground(new java.awt.Color(235, 238, 241));
        pnlVuelo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVueloIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlVuelo.add(lblVueloIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vuelos");
        pnlVuelo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 70, 150, 150));

        pnlSalir.setBackground(new java.awt.Color(235, 238, 241));
        pnlSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalirIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlSalir.add(lblSalirIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Salir");
        pnlSalir.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 290, 150, 150));

        pnlAyuda.setBackground(new java.awt.Color(235, 238, 241));
        pnlAyuda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAyudaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlAyuda.add(lblAyudaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel14.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ayuda");
        pnlAyuda.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 290, 150, 150));

        pnlAvion.setBackground(new java.awt.Color(235, 238, 241));
        pnlAvion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlAvion.add(lblAvionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel16.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Aviones");
        pnlAvion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jPanel3.add(pnlAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 70, 150, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 185, 990, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public componente.Boton btnMinimizar;
    public componente.Boton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblAvionIcon;
    public javax.swing.JLabel lblAyudaIcon;
    public javax.swing.JLabel lblConfigIcon;
    public javax.swing.JLabel lblLogoIcon;
    public javax.swing.JLabel lblSalirIcon;
    public javax.swing.JLabel lblTripulacionIcon;
    public javax.swing.JLabel lblUsuarioIcon;
    public javax.swing.JLabel lblVentaIcon;
    public javax.swing.JLabel lblVueloIcon;
    public javax.swing.JPanel pnlAvion;
    public javax.swing.JPanel pnlAyuda;
    public javax.swing.JPanel pnlConfig;
    public javax.swing.JPanel pnlSalir;
    public javax.swing.JPanel pnlTripulacion;
    public javax.swing.JPanel pnlUsuario;
    public javax.swing.JPanel pnlVenta;
    public javax.swing.JPanel pnlVuelo;
    // End of variables declaration//GEN-END:variables
}
