/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;

/**
 *
 * @author Vinicio
 */
public class vPVentas extends javax.swing.JFrame {

    /**
     * Creates new form vUsuario
     */
    public vPVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnPVentas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        Inicio = new javax.swing.JPanel();
        jLabelBigLogo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        Ventas = new javax.swing.JPanel();
        jPanelHV4 = new javax.swing.JPanel();
        JlHVIcon = new javax.swing.JLabel();
        jlbPV = new javax.swing.JLabel();
        SeleccionTodo = new javax.swing.JPanel();
        jPanelSDatos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jcomboxTIdaRedondo = new javax.swing.JComboBox<>();
        jLOrigen = new javax.swing.JLabel();
        ComboBoxOrigen = new javax.swing.JComboBox<>();
        jLDestino = new javax.swing.JLabel();
        ComboBoxDestino = new javax.swing.JComboBox<>();
        jLSalida = new javax.swing.JLabel();
        jLRetorn = new javax.swing.JLabel();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jDateChooserRetorno = new com.toedter.calendar.JDateChooser();
        jLRetorno = new javax.swing.JLabel();
        btnBuscarVuelos = new javax.swing.JButton();
        jPanelRedondo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRedondoIda = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRedondoRegreso = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelIda = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableIDAIDA = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLCosto = new javax.swing.JLabel();
        jTextCosto = new javax.swing.JTextField();
        btnAsientos = new javax.swing.JButton();
        jComboBoxSPago = new javax.swing.JComboBox<>();
        jButtonPagar = new javax.swing.JButton();
        lblErrorDeAsientos = new javax.swing.JLabel();
        PagoTarjeta = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlbPago1 = new javax.swing.JLabel();
        JlPagoIcon1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextNomT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextPAN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextCVC = new javax.swing.JTextField();
        btnRegresarTarjeta = new javax.swing.JButton();
        jLCantiPagar = new javax.swing.JLabel();
        btnRPago = new javax.swing.JButton();
        txtPagoFinal = new javax.swing.JTextField();
        jLabelTTarjeta = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTarjetaError = new javax.swing.JLabel();
        pnlEfectivo = new javax.swing.JPanel();
        btnExplorar = new javax.swing.JButton();
        btnImprimirReporte = new javax.swing.JButton();
        lblAsientosPagar = new javax.swing.JLabel();
        lblVueloInfo = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        lblVueloHora = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pnlAsientos1 = new javax.swing.JPanel();
        pnlImg1 = new javax.swing.JScrollPane();
        lblAsientos = new javax.swing.JLabel();
        lblNombreCliente1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        spnMenor = new javax.swing.JSpinner();
        spnAdulto = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        cmbSeleccion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnFaq = new javax.swing.JButton();
        pnlFaq = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnSalirPrograma = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(213, 216, 223));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 216, 223), 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(240, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 45, 215, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TODOS LOS DERECHOS RESERVADOS");
        jPanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 505, 215, 20));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VOYAGER AIRLINES");
        jPanelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 525, 215, 20));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Versión 1.0");
        jPanelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 545, 215, 20));

        btnInicio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnInicio.setText("Inicio");
        jPanelMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 65, 215, 40));

        btnPVentas.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnPVentas.setText("Ventas");
        jPanelMenu.add(btnPVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 215, 40));

        btnCerrar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnCerrar.setText("Cerrar sesión");
        jPanelMenu.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 455, 215, 40));

        lblFecha.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("29 de Marzo de 2018");
        jPanelMenu.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        jPanelContenedor.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 225, 570));

        Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBigLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inicio.add(jLabelBigLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 495, 330));

        lblNombre.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre apellido, cargo");
        Inicio.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 730, 40));

        jPanelContenedor.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 10, 735, 570));

        Ventas.setBackground(new java.awt.Color(255, 255, 255));
        Ventas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Ventas.setMinimumSize(new java.awt.Dimension(733, 550));
        Ventas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHV4.setBackground(new java.awt.Color(213, 216, 223));
        jPanelHV4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlHVIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelHV4.add(JlHVIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        jlbPV.setFont(new java.awt.Font("Sitka Small", 1, 28)); // NOI18N
        jlbPV.setForeground(new java.awt.Color(63, 136, 143));
        jlbPV.setText("PUNTO DE VENTA");
        jPanelHV4.add(jlbPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 300, 60));

        Ventas.add(jPanelHV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 730, 80));

        SeleccionTodo.setBackground(new java.awt.Color(213, 216, 223));

        jPanelSDatos.setBackground(new java.awt.Color(213, 216, 223));

        jLabel9.setText("Tipo:");

        jcomboxTIdaRedondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Redondo", "Ida" }));

        jLOrigen.setText("Origen:");

        ComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOrigenActionPerformed(evt);
            }
        });

        jLDestino.setText("Destino:");

        ComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLSalida.setText("Salida:");

        jLRetorn.setText("Retorno:");

        jLRetorno.setText("Retorno:");
        
        jDateChooserSalida.setDateFormatString("yyyy-MM-d");

        jDateChooserRetorno.setDateFormatString("yyyy-MM-dd");

        btnBuscarVuelos.setText("Buscar Vuelos");

        javax.swing.GroupLayout jPanelSDatosLayout = new javax.swing.GroupLayout(jPanelSDatos);
        jPanelSDatos.setLayout(jPanelSDatosLayout);
        jPanelSDatosLayout.setHorizontalGroup(
            jPanelSDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSalida)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSDatosLayout.createSequentialGroup()
                        .addComponent(jcomboxTIdaRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSDatosLayout.createSequentialGroup()
                        .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLRetorn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(jLRetorno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarVuelos)
                        .addGap(38, 38, 38))))
        );
        jPanelSDatosLayout.setVerticalGroup(
            jPanelSDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelSDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcomboxTIdaRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLOrigen)
                    .addComponent(ComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDestino)
                    .addComponent(ComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelSDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSalida)
                    .addComponent(jLRetorn)
                    .addComponent(jDateChooserRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRetorno)
                    .addComponent(btnBuscarVuelos))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelRedondo.setBackground(new java.awt.Color(213, 216, 223));

        jLabel10.setText("Selección de Vuelo:");

        jTableRedondoIda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRedondoIda);

        jTableRedondoRegreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableRedondoRegreso);

        jLabel6.setText("IDA");

        jLabel7.setText("RETORNO");

        javax.swing.GroupLayout jPanelRedondoLayout = new javax.swing.GroupLayout(jPanelRedondo);
        jPanelRedondo.setLayout(jPanelRedondoLayout);
        jPanelRedondoLayout.setHorizontalGroup(
            jPanelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRedondoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelRedondoLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(169, 169, 169))
        );
        jPanelRedondoLayout.setVerticalGroup(
            jPanelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRedondoLayout.createSequentialGroup()
                .addGroup(jPanelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanelRedondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelIda.setBackground(new java.awt.Color(213, 216, 223));

        jLabel11.setText("Selección de Vuelo:");

        jTableIDAIDA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableIDAIDA);

        jLabel8.setText("IDA");

        javax.swing.GroupLayout jPanelIdaLayout = new javax.swing.GroupLayout(jPanelIda);
        jPanelIda.setLayout(jPanelIdaLayout);
        jPanelIdaLayout.setHorizontalGroup(
            jPanelIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdaLayout.createSequentialGroup()
                .addGroup(jPanelIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIdaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel8))
                    .addGroup(jPanelIdaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelIdaLayout.setVerticalGroup(
            jPanelIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdaLayout.createSequentialGroup()
                .addGroup(jPanelIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanelIdaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLCosto.setText("Costo:");

        jTextCosto.setText("Costo");

        btnAsientos.setText("Asientos");

        jComboBoxSPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Terjeta" }));

        jButtonPagar.setText("Pagar");

        javax.swing.GroupLayout SeleccionTodoLayout = new javax.swing.GroupLayout(SeleccionTodo);
        SeleccionTodo.setLayout(SeleccionTodoLayout);
        SeleccionTodoLayout.setHorizontalGroup(
            SeleccionTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionTodoLayout.createSequentialGroup()
                .addComponent(jPanelRedondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionTodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSPago, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDeAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsientos)
                .addGap(25, 25, 25))
            .addGroup(SeleccionTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SeleccionTodoLayout.createSequentialGroup()
                    .addComponent(jPanelIda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        SeleccionTodoLayout.setVerticalGroup(
            SeleccionTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionTodoLayout.createSequentialGroup()
                .addComponent(jPanelSDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeleccionTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCosto)
                    .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsientos)
                    .addComponent(jComboBoxSPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPagar)
                    .addComponent(lblErrorDeAsientos))
                .addContainerGap())
            .addGroup(SeleccionTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SeleccionTodoLayout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jPanelIda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        Ventas.add(SeleccionTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 710, 470));

        jPanel5.setBackground(new java.awt.Color(213, 216, 223));

        jlbPago1.setFont(new java.awt.Font("Sitka Small", 1, 28)); // NOI18N
        jlbPago1.setForeground(new java.awt.Color(63, 136, 143));
        jlbPago1.setText("PAGO CON TARJETA");

        JlPagoIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlPagoIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPago1)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlPagoIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Nombre del Titular:");

        jTextNomT.setText("Nombre");

        jLabel13.setText("Fecha de Espiracion:");

        jTextFecha.setText("Fecha");

        jLabel14.setText("PAN (Num. de Tarjeta):");

        jTextPAN.setText("PAN");

        jLabel15.setText("Codigo de Seguridad(CVC):");

        jTextCVC.setText("CVC");

        btnRegresarTarjeta.setText("Regresar");

        jLCantiPagar.setText("Cantidad a Pagar:");

        btnRPago.setText("Realizar Pago");

        txtPagoFinal.setText("Pago");

        jLabelTTarjeta.setText("Tipo de Tarjeta");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MarterCard", "Visa" }));

        javax.swing.GroupLayout PagoTarjetaLayout = new javax.swing.GroupLayout(PagoTarjeta);
        PagoTarjeta.setLayout(PagoTarjetaLayout);
        PagoTarjetaLayout.setHorizontalGroup(
            PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PagoTarjetaLayout.createSequentialGroup()
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagoTarjetaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabelTTarjeta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextPAN)
                                .addComponent(jTextNomT, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                            .addComponent(jTextCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PagoTarjetaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnRegresarTarjeta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagoTarjetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLCantiPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPagoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnRPago)
                .addGap(23, 23, 23))
            .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PagoTarjetaLayout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(lblTarjetaError, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        PagoTarjetaLayout.setVerticalGroup(
            PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagoTarjetaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextNomT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTTarjeta)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRPago)
                    .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCantiPagar)
                        .addComponent(txtPagoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(btnRegresarTarjeta)
                .addContainerGap())
            .addGroup(PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PagoTarjetaLayout.createSequentialGroup()
                    .addGap(324, 324, 324)
                    .addComponent(lblTarjetaError)
                    .addContainerGap(146, Short.MAX_VALUE)))
        );

        Ventas.add(PagoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 710, 470));

        btnExplorar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnExplorar.setText("Guardar como pdf");

        btnImprimirReporte.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnImprimirReporte.setText("Imprimir");

        lblAsientosPagar.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblAsientosPagar.setText("Asientos: ");

        lblVueloInfo.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblVueloInfo.setText("Vuelo");

        lblPrecioTotal.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblPrecioTotal.setText("Total: ");

        lblVueloHora.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblVueloHora.setText("Hora: ");

        jLabel31.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel31.setText("<html><p align = \"justify\">Al hacer clic en uno de los botones sus asientos quedarán reservados. Después de esto, usted cuenta con un plazo máximo de 72 horas para efectuar el pago de sus boletos, de lo contrario, los asientos que seleccionó serán marcados como disponibles de nuevo y su reporte quedará inválido</p>.</html>");

        javax.swing.GroupLayout pnlEfectivoLayout = new javax.swing.GroupLayout(pnlEfectivo);
        pnlEfectivo.setLayout(pnlEfectivoLayout);
        pnlEfectivoLayout.setHorizontalGroup(
            pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEfectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEfectivoLayout.createSequentialGroup()
                        .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioTotal)
                            .addComponent(btnImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEfectivoLayout.createSequentialGroup()
                        .addGroup(pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVueloHora)
                            .addComponent(lblVueloInfo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblAsientosPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlEfectivoLayout.setVerticalGroup(
            pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEfectivoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblVueloInfo)
                .addGap(40, 40, 40)
                .addComponent(lblAsientosPagar)
                .addGap(40, 40, 40)
                .addComponent(lblVueloHora)
                .addGap(50, 50, 50)
                .addComponent(lblPrecioTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnImprimirReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(btnExplorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Ventas.add(pnlEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jPanelContenedor.add(Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 10, 730, 570));

        pnlAsientos1.setBackground(new java.awt.Color(255, 255, 255));
        pnlAsientos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlImg1.setViewportView(lblAsientos);

        pnlAsientos1.add(pnlImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 322, 570));

        lblNombreCliente1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        pnlAsientos1.add(lblNombreCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel16.setText("Niños:");
        pnlAsientos1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 204, -1, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel17.setText("Adultos:");
        pnlAsientos1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 253, -1, -1));

        spnMenor.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        spnMenor.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        pnlAsientos1.add(spnMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        spnAdulto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        spnAdulto.setModel(new javax.swing.SpinnerNumberModel(1, 0, 99, 1));
        pnlAsientos1.add(spnAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel18.setText("Selección:");
        pnlAsientos1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 443, -1, -1));

        cmbSeleccion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Múltiple", "Individual" }));
        cmbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionActionPerformed(evt);
            }
        });
        pnlAsientos1.add(cmbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 438, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(19, 19));
        pnlAsientos1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel19.setText("Asiento deseado");
        pnlAsientos1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 133, -1, -1));

        jButton2.setPreferredSize(new java.awt.Dimension(19, 19));
        pnlAsientos1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel20.setText("Asiento ocupado");
        pnlAsientos1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 33, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 32, 209));
        jButton3.setPreferredSize(new java.awt.Dimension(19, 19));
        pnlAsientos1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel21.setText("Asiento disponible");
        pnlAsientos1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 83, -1, -1));

        btnFaq.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnFaq.setBorder(null);
        btnFaq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFaq.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlAsientos1.add(btnFaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        pnlFaq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel22.setText("Múltiple: Permite seleccionar varios ");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlFaq.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 268, -1));

        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel23.setText("asientos con un solo clic.");
        pnlFaq.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        jLabel24.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel24.setText("Individual: Permite seleccionar los");
        pnlFaq.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        jLabel25.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel25.setText("asientos uno por uno.");
        pnlFaq.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, -1, -1));

        pnlAsientos1.add(pnlFaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 250, 120));

        btnContinuar.setBackground(new java.awt.Color(0, 32, 209));
        btnContinuar.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("¡Continuar! ");
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlAsientos1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 170, 50));

        jLabel26.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel26.setText("Subtotal:");
        pnlAsientos1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 228, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lblPrecio.setText("$5000");
        pnlAsientos1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 226, -1, -1));

        jPanelContenedor.add(pnlAsientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 10, 735, 570));

        jPanel1.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 105, 990, 590));

        btnSalirPrograma.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirPrograma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalirPrograma.setText("X");
        jPanel1.add(btnSalirPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 50));

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMinimizar.setText("-");
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 50, 50));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 85, 85));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("VOYAGER AIRLINES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 30, 450, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxOrigenActionPerformed

    private void cmbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxDestino;
    public javax.swing.JComboBox<String> ComboBoxOrigen;
    public javax.swing.JPanel Inicio;
    public javax.swing.JLabel JlHVIcon;
    public javax.swing.JLabel JlPagoIcon1;
    public javax.swing.JPanel PagoTarjeta;
    public javax.swing.JPanel SeleccionTodo;
    public javax.swing.JPanel Ventas;
    public javax.swing.JButton btnAsientos;
    public javax.swing.JButton btnBuscarVuelos;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnContinuar;
    public javax.swing.JButton btnExplorar;
    public javax.swing.JButton btnFaq;
    public javax.swing.JButton btnImprimirReporte;
    public javax.swing.JButton btnInicio;
    public javax.swing.JButton btnMinimizar;
    public javax.swing.JButton btnPVentas;
    public javax.swing.JButton btnRPago;
    public javax.swing.JButton btnRegresarTarjeta;
    public javax.swing.JButton btnSalirPrograma;
    public javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButtonPagar;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBoxSPago;
    public javax.swing.JLabel jLCantiPagar;
    private javax.swing.JLabel jLCosto;
    private javax.swing.JLabel jLDestino;
    private javax.swing.JLabel jLOrigen;
    public javax.swing.JLabel jLRetorn;
    private javax.swing.JLabel jLSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelBigLogo;
    public javax.swing.JLabel jLabelTTarjeta;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelHV4;
    public javax.swing.JPanel jPanelIda;
    private javax.swing.JPanel jPanelMenu;
    public javax.swing.JPanel jPanelRedondo;
    private javax.swing.JPanel jPanelSDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTableIDAIDA;
    public javax.swing.JTable jTableRedondoIda;
    public javax.swing.JTable jTableRedondoRegreso;
    public javax.swing.JTextField jTextCVC;
    public javax.swing.JTextField jTextCosto;
    public javax.swing.JTextField jTextFecha;
    public javax.swing.JTextField jTextNomT;
    public javax.swing.JTextField jTextPAN;
    public javax.swing.JComboBox<String> jcomboxTIdaRedondo;
    private javax.swing.JLabel jlbPV;
    private javax.swing.JLabel jlbPago1;
    public javax.swing.JLabel lblAsientos;
    public javax.swing.JLabel lblAsientosPagar;
    public javax.swing.JLabel lblErrorDeAsientos;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblLogo;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblNombreCliente1;
    public javax.swing.JLabel lblPrecio;
    public javax.swing.JLabel lblPrecioTotal;
    public javax.swing.JLabel lblTarjetaError;
    public javax.swing.JLabel lblVueloHora;
    public javax.swing.JLabel lblVueloInfo;
    public javax.swing.JPanel pnlAsientos1;
    public javax.swing.JPanel pnlEfectivo;
    public javax.swing.JPanel pnlFaq;
    public javax.swing.JScrollPane pnlImg1;
    public javax.swing.JSpinner spnAdulto;
    public javax.swing.JSpinner spnMenor;
    public javax.swing.JTextField txtPagoFinal;
    // End of variables declaration//GEN-END:variables
    public JDateChooser jDateChooserSalida = new JDateChooser();
    public JDateChooser jDateChooserRetorno = new JDateChooser();
    public javax.swing.JLabel jLRetorno;
}

