/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author aldah
 */
public class vUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form vUsuarios
     */
    public vUsuarios() {
//        initComponents();
//        this.setLocationRelativeTo(null);
//        ImageIcon avion_logo = new ImageIcon(getClass().getResource(("/img/avion_logo.png")));
//        ImageIcon usuario = new ImageIcon(getClass().getResource(("/img/usuario.png")));
//        
//        ImageIcon logotipo = new ImageIcon(avion_logo.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_DEFAULT));
//        ImageIcon user = new ImageIcon(usuario.getImage().getScaledInstance(jLabelUsuarioImagenu.getWidth(), jLabelUsuarioImagenu.getHeight(), Image.SCALE_DEFAULT));
//        
//        jLabelLogo.setIcon(logotipo);
//        jLabelUsuarioImagenu.setIcon(user);
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperioru = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelNombreLogou5 = new javax.swing.JLabel();
        jLabelSeccionu = new javax.swing.JLabel();
        jButtonSaliru = new javax.swing.JButton();
        jPanelMenuu = new javax.swing.JPanel();
        jLabelUsuarioImagenu = new javax.swing.JLabel();
        jSeparator1u = new javax.swing.JSeparator();
        jSeparator2u = new javax.swing.JSeparator();
        jLabelNombreUseru = new javax.swing.JLabel();
        jButton1u = new javax.swing.JButton();
        jButton2u = new javax.swing.JButton();
        jButton3u = new javax.swing.JButton();
        jButton4u = new javax.swing.JButton();
        jButton5u = new javax.swing.JButton();
        jButton6u = new javax.swing.JButton();
        jLabelNombreLogou1 = new javax.swing.JLabel();
        jLabelNombreLogou4 = new javax.swing.JLabel();
        jPanel6u = new javax.swing.JPanel();
        jButton5uu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSuperioru.setBackground(new java.awt.Color(128, 0, 0));

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelNombreLogou5.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabelNombreLogou5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreLogou5.setText("Nombre de usuario:");

        jLabelSeccionu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelSeccionu.setForeground(new java.awt.Color(255, 255, 255));

        jButtonSaliru.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSaliru.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaliru.setText("X");
        jButtonSaliru.setContentAreaFilled(false);
        jButtonSaliru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaliru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaliruActionPerformed(evt);
            }
        });

        jPanelMenuu.setBackground(new java.awt.Color(128, 0, 0));

        jLabelNombreUseru.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        jLabelNombreUseru.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNombreUseru.setText("Nombre de usuario");

        jButton1u.setBackground(new java.awt.Color(128, 0, 0));
        jButton1u.setForeground(new java.awt.Color(255, 255, 255));
        jButton1u.setText("Inicio");

        jButton2u.setBackground(new java.awt.Color(128, 0, 0));
        jButton2u.setForeground(new java.awt.Color(255, 255, 255));
        jButton2u.setText("Aviones");

        jButton3u.setBackground(new java.awt.Color(255, 0, 0));
        jButton3u.setForeground(new java.awt.Color(255, 255, 255));
        jButton3u.setText("Usuarios");

        jButton4u.setBackground(new java.awt.Color(128, 0, 0));
        jButton4u.setForeground(new java.awt.Color(255, 255, 255));
        jButton4u.setText("Ventas");
        jButton4u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4uActionPerformed(evt);
            }
        });

        jButton5u.setBackground(new java.awt.Color(128, 0, 0));
        jButton5u.setForeground(new java.awt.Color(204, 204, 204));
        jButton5u.setText("Vuelos");
        jButton5u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5uActionPerformed(evt);
            }
        });

        jButton6u.setBackground(new java.awt.Color(128, 0, 0));
        jButton6u.setForeground(new java.awt.Color(255, 255, 255));
        jButton6u.setText("Cerrar sesión");

        javax.swing.GroupLayout jPanelMenuuLayout = new javax.swing.GroupLayout(jPanelMenuu);
        jPanelMenuu.setLayout(jPanelMenuuLayout);
        jPanelMenuuLayout.setHorizontalGroup(
            jPanelMenuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreUseru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1u)
                    .addComponent(jSeparator2u))
                .addContainerGap())
            .addComponent(jButton1u, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMenuuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelUsuarioImagenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelMenuuLayout.setVerticalGroup(
            jPanelMenuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelUsuarioImagenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1u, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelNombreUseru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2u, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1u, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton2u, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3u, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton4u, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton5u, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jButton6u, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelNombreLogou1.setFont(new java.awt.Font("Century Schoolbook", 2, 36)); // NOI18N
        jLabelNombreLogou1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreLogou1.setText("VOYAGER AIRLINES");

        jLabelNombreLogou4.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabelNombreLogou4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreLogou4.setText("Busqueda de usuarios.");

        javax.swing.GroupLayout jPanel6uLayout = new javax.swing.GroupLayout(jPanel6u);
        jPanel6u.setLayout(jPanel6uLayout);
        jPanel6uLayout.setHorizontalGroup(
            jPanel6uLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        jPanel6uLayout.setVerticalGroup(
            jPanel6uLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jButton5uu.setBackground(new java.awt.Color(128, 0, 0));
        jButton5uu.setForeground(new java.awt.Color(204, 204, 204));
        jButton5uu.setText("Buscar");
        jButton5uu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5uuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperioruLayout = new javax.swing.GroupLayout(jPanelSuperioru);
        jPanelSuperioru.setLayout(jPanelSuperioruLayout);
        jPanelSuperioruLayout.setHorizontalGroup(
            jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                .addComponent(jPanelMenuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaliru))
                    .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabelNombreLogou5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5uu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(jLabelSeccionu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperioruLayout.createSequentialGroup()
                    .addContainerGap(363, Short.MAX_VALUE)
                    .addComponent(jLabelNombreLogou1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(343, 343, 343)))
            .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperioruLayout.createSequentialGroup()
                    .addContainerGap(462, Short.MAX_VALUE)
                    .addComponent(jLabelNombreLogou4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(244, 244, 244)))
        );
        jPanelSuperioruLayout.setVerticalGroup(
            jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                .addComponent(jButtonSaliru, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSeccionu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreLogou5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton5uu)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                .addComponent(jPanelMenuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabelNombreLogou1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(532, Short.MAX_VALUE)))
            .addGroup(jPanelSuperioruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSuperioruLayout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jLabelNombreLogou4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSuperioru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelSuperioru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaliruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaliruActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSaliruActionPerformed

    private void jButton4uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4uActionPerformed

    private void jButton5uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5uActionPerformed

    private void jButton5uuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5uuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5uuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1u;
    private javax.swing.JButton jButton2u;
    private javax.swing.JButton jButton3u;
    private javax.swing.JButton jButton4u;
    private javax.swing.JButton jButton5u;
    private javax.swing.JButton jButton5uu;
    private javax.swing.JButton jButton6u;
    private javax.swing.JButton jButtonSaliru;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombreLogou1;
    private javax.swing.JLabel jLabelNombreLogou4;
    private javax.swing.JLabel jLabelNombreLogou5;
    private javax.swing.JLabel jLabelNombreUseru;
    public javax.swing.JLabel jLabelSeccionu;
    private javax.swing.JLabel jLabelUsuarioImagenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6u;
    private javax.swing.JPanel jPanelMenuu;
    private javax.swing.JPanel jPanelSuperioru;
    private javax.swing.JSeparator jSeparator1u;
    private javax.swing.JSeparator jSeparator2u;
    // End of variables declaration//GEN-END:variables
}
